# 配置语言及相应版本
language: node_js
node_js: stable

# 项目所在分支
branches:
  only:
    - master

cache:
  apt: true
  directories:
    - node_modules # 缓存不经常更改的内容

# 配置环境
before_install:
  - export TZ='Asia/Shanghai' # 更改时区

# 安装依赖
install:
  - npm config set registry https://registry.npm.taobao.org
  - npm install hexo-cli -g
  - npm install

# 部署的命令
script:
  - npm run generate # hexo clean && hexo g

after_script:
  - git clone https://${GH_REF} .deploy_git # GH_REF是最下面配置的仓库地址
  - cd .deploy_git
  - git checkout master
  - cd ../
  - mv .deploy_git/.git/ ./public/ # 这一步之前的操作是为了保留master分支的提交记录，不然每次git init的话只有1条commit
  - cd ./public
  - git config user.name "saobei" #修改name
  - git config user.email "huyouming@lcsw.cn" #修改email
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`" # 提交记录包含时间 跟上面更改时区配合
  - git push --force --quiet "https://${blog}@${GH_REF}" master:gh-pages #Travis_Token是在Travis中配置环境变量的名称

# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#   keep_history: true
#   on:
#     branch: gh-pages

env:
  global:
    - GH_REF: github.com/saobei/blog.git #设置GH_REF，注意更改yourname
    - secure: "EKiXKEkA3bNzWuxqWi+zLlIafN7IqQ+3UPXfcdgshKia3fKbN2bBfav2W9jCME919efXvHiYzmhVNSnT+lkkzVVqWP+50al94oJ6S60qa8DehLqHgyXRsSQXJVtOgwMANkKiiM+di6TicmLQVz20FzBFUi2vFZ9007CXyfc2MK2FTOuS++ciJuWRyXgyLpRhA/Li1kTk+5ORNqIWSGSql208NB5ALp7fqzmCZG+xQi2JveTPKgZbKbmLEC2UwE7BNHnmuvltlw8QIvIkFHkmJo4s93CAu0KBH8yYMoTO6QCtvzYqFJHea0nVG6vckUaKzJZFqyGClzWCaKB8FNDCpk0958Ldi9ziELbYE+mfLE9z87YYPcZRXTTPVfIO3qSewxEZISVUW6VASuVxFW1VWGtYxQe4rdmuGrEsOrYtUIVIu14Xa0oJS6xBVfE2+LoRDGBm339XyTRFzEol/IKjRLcZaSmnG6KPCoDBLnHzzLhOaKw9M6F+6bayVfhVzFSDkmT8MWtK+ZzXu/esp05c5c1zUB85OxFXYflkrK9yrFwOp9uGZsdrXmAthEE+PwGdnfren8ZsaRmi7dlLQYtF7l2Z1Lu/CtkXqhDRaiIyzCm/JBl3kC+9smOJS1HPm3fGIGzKMnYpJ0Zn6MbfcrcolrsjTxvD9K8FuF+c/Q+oNIM="
